name: Nightly build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["Release", "Debug"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1.0.3
      with:
        ndk-version: r22b

    # Copied from sc2ad :)
    - name: Get QPM
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: main.yml
        name: QPM-ubuntu-x64
        path: QPM
        repo: sc2ad/QuestPackageManager
    - name: QPM Collect
      run: |
        chmod +x ./QPM/QPM
        ./QPM/QPM collect
    - name: QPM Dependencies Cache
      id: cache-qpm-deps
      uses: actions/cache@v2
      env:
        cache-name: cache-qpm-deps
      with:
        path: QPM_Temp
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('qpm.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: QPM Restore
      run: ./QPM/QPM restore
    - name: List Post Restore
      run: |
        ls -la ${GITHUB_WORKSPACE}/extern/
        ls -la QPM_Temp

    - name: Build for ${{ matrix.target }}
      run: ./build.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        CI_BUILD_TARGET: ${{ matrix.target }}
    - name: Package for ${{ matrix.target }}
      run: ./release-qmod.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        CI_BUILD_TARGET: ${{ matrix.target }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ParticleTuner.${{ matrix.target }}
        path: |
          *.qmod
        if-no-files-found: error
